const fs = require("fs");
const base = "C:/claude27/Flashcardv1/app";
const lines = [];
lines.push("import { Navbar } from \"@/components/layout/Navbar\";");
lines.push("import { Footer } from \"@/components/layout/Footer\";");
lines.push("import { Button } from \"@/components/ui/button\";");
lines.push("import {");
lines.push("  Accordion,");
lines.push("  AccordionContent,");
lines.push("  AccordionItem,");
lines.push("  AccordionTrigger,");
lines.push("} from \"@/components/ui/accordion\";");
lines.push("import { HelpCircle, MessageCircle } from \"lucide-react\";");
lines.push("import Link from \"next/link\";");
lines.push("");
lines.push("const faqSections = [");
lines.push("  {");
lines.push("    id: \"general\",");
lines.push("    label: \"General\",");
lines.push("    badgeColor: \"bg-blue-100 text-blue-700 border border-blue-200\",");
lines.push("    questions: [");
