const fs = require("fs");
const p = (s) => s;
const j = (...a) => a.join("\n");
const base = "C:/claude27/Flashcardv1/app";

// apostrophe helper
const apos = String.fromCharCode(39);

// ===== FAQ PAGE =====
const faq = j(
p("import { Navbar } from \"@/components/layout/Navbar\";"),
p("import { Footer } from \"@/components/layout/Footer\";"),
p("import { Button } from \"@/components/ui/button\";"),
p("import {"),
p("  Accordion,"),
p("  AccordionContent,"),
p("  AccordionItem,"),
p("  AccordionTrigger,"),
p("} from \"@/components/ui/accordion\";"),
p("import { HelpCircle, MessageCircle } from \"lucide-react\";"),
p("import Link from \"next/link\";"),
p(""),
p("const faqSections = ["),
p("  {"),
p("    id: \"general\","),
p("    label: \"General\","),
p("    badgeColor: \"bg-blue-100 text-blue-700 border border-blue-200\","),
p("    questions: ["),
p("      {"),
p("        id: \"what-is-kognitdeck\","),
p("        question: \"What is KognitDeck?\","),
p("        answer:"),
p("          \"KognitDeck is an AI-powered flashcard platform that lets you generate, study, and quiz yourself on any topic in seconds. Simply enter a subject or paste your notes and our AI will create a full set of flashcards tailored to your learning goals. Whether you are a student cramming for exams or a professional brushing up on new skills, KognitDeck makes studying faster and smarter.\","),
p("      },"),
p("      {"),
p("        id: \"how-ai-generates\","),
p("        question: \"How does AI generate flashcards?\","),
p("        answer:"),
p("          \"KognitDeck uses large language models (LLMs) to analyze the topic or text you provide. The AI identifies key concepts, definitions, and relationships, then structures them into clear question-and-answer pairs or multiple-choice questions. The generation process typically takes 5 to 15 seconds and produces 10 to 20 cards per session.\","),
p("      },"),
p("      {"),
p("        id: \"mobile-app\","),
p("        question: \"Is there a mobile app?\","),
p("        answer:"),
p("          \"KognitDeck is a fully responsive web application that works great on mobile browsers with no download required. Simply visit the app on your phone or tablet and you will get a native-like experience. A dedicated iOS and Android app is on our roadmap for 2026.\","),
p("      },"),
p("      {"),
p("        id: \"languages-supported\","),
p("        question: \"What languages are supported?\","),
p("        answer:"),
p("          \"KognitDeck supports topic generation and flashcard creation in over 30 languages including English, Spanish, French, German, Portuguese, Mandarin, Japanese, Korean, Arabic, and more. Localization for additional interface languages is planned in upcoming releases.\","),
p("      },"),
p("      {"),
p("        id: \"how-to-get-started\","),
p("        question: \"How do I get started?\","),
p("        answer:"),
p("          \"Getting started is simple. Create a free account using your email or Google sign-in, then click Generate Cards from your dashboard. Enter any topic and hit Generate. Your first set of flashcards will be ready in seconds. The free plan includes unlimited Q and A card generation, and you can upgrade to Pro for multiple-choice quizzes and advanced features.\","),
p("      },"),
p("    ],"),
p("  },"),
p("  {"),
p("    id: \"features\","),
p("    label: \"Features\","),
p("    badgeColor: \"bg-purple-100 text-purple-700 border border-purple-200\","),
p("    questions: ["),
p("      {"),
p("        id: \"qa-vs-mcq\","),
p("        question: \"What is the difference between Q\u0026A and MCQ modes?\","),
p("        answer:"),
p("          \"Q\u0026A mode presents you with a question and you recall the answer before flipping the card to check. This is great for open recall practice. MCQ (Multiple Choice Question) mode presents you with a question and four answer options simulating real exam conditions. MCQ mode is a Pro feature especially useful for standardized test prep.\","),
p("      },"),
p("      {"),
p("        id: \"edit-generated-cards\","),
p("        question: \"Can I edit generated cards?\","),
p("        answer:"),
p("          \"Yes\! Every generated flashcard is fully editable. After your set is generated, click on any card to open the editor where you can modify the question, answer, or answer choices. You can also delete cards, reorder them, or add new cards manually. Your edits are saved automatically.\","),
p("      },"),
p("      {"),
p("        id: \"how-study-mode-works\","),
p("        question: \"How does study mode work?\","),
p("        answer:"),
p("          \"Study mode presents your flashcards one at a time in a clean, distraction-free interface. You can flip each card to reveal the answer, then mark it as Got it or Still learning. KognitDeck tracks your progress across sessions and prioritizes cards you struggle with using a spaced repetition algorithm, so your study time is always focused where it matters most.\","),
p("      },"),
p("      {"),
p("        id: \"quiz-paywall\","),
p("        question: \"What is behind the quiz paywall?\","),
p("        answer:"),
p("          \"The Pro subscription unlocks the full Quiz mode, which includes timed multiple-choice quizzes, a score summary at the end, and a detailed breakdown of which questions you got right or wrong. It also unlocks unlimited saved decks, the ability to share decks publicly, advanced topic generation with subtopics, and priority AI generation speed.\","),
p("      },"),
p("      {"),
p("        id: \"topic-generation\","),
p("        question: \"What is topic generation?\","),
p("        answer:"),
p("          \"Topic generation is KognitDeck" + apos + "s core feature. You type a subject, anything from Organic Chemistry basics to The French Revolution, and the AI generates a structured deck of flashcards on that topic from scratch. Pro users can generate cards with subtopic breakdowns, creating hierarchical decks covering a subject in depth.\","),
p("      },"),
p("    ],"),
p("  },"),
p("  {"),
p("    id: \"billing\","),
p("    label: \"Billing\","),
p("    badgeColor: \"bg-green-100 text-green-700 border border-green-200\","),
p("    questions: ["),
p("      {"),
p("        id: \"cancel-anytime\","),
p("        question: \"Can I cancel my subscription anytime?\","),
p("        answer:"),
p("          \"Yes, absolutely. You can cancel your Pro subscription at any time from your account settings under the Billing tab. When you cancel, you retain Pro access until the end of your current billing period. After that, your account reverts to the free plan. There are no cancellation fees or penalties.\","),
p("      },"),
p("      {"),
p("        id: \"student-discount\","),
p("        question: \"Is there a student discount?\","),
p("        answer:"),
p("          \"Yes\! Students with a valid .edu email address receive 30% off the Pro monthly plan and 40% off the annual plan. Sign up or log in with your .edu email and the discount will be applied automatically at checkout. If your institution uses a different email domain, contact our support team and we will verify your student status manually.\","),
p("      },"),
p("      {"),
p("        id: \"payment-methods\","),
p("        question: \"What payment methods do you accept?\","),
p("        answer:"),
p("          \"KognitDeck accepts all major credit and debit cards (Visa, Mastercard, American Express, Discover) as well as Apple Pay and Google Pay. All payments are processed securely through Stripe, a PCI-compliant payment processor. We do not store your card details on our servers.\","),
p("      },"),
p("      {"),
p("        id: \"data-after-cancel\","),
p("        question: \"What happens to my data if I cancel?\","),
p("        answer:"),
p("          \"Your account and all of your flashcard decks remain intact after cancellation. You simply lose access to Pro-only features like MCQ mode and timed quizzes. Your decks are never deleted automatically. If you choose to permanently delete your account, we will erase your data within 30 days. You can export all your decks as JSON or CSV at any time from account settings.\","),
p("      },"),
p("    ],"),
p("  },"),
p("  {"),
p("    id: \"privacy-section\","),
p("    label: \"Privacy\","),
p("    badgeColor: \"bg-orange-100 text-orange-700 border border-orange-200\","),
p("    questions: ["),
p("      {"),
p("        id: \"data-secure\","),
p("        question: \"Is my data secure?\","),
p("        answer:"),
p("          \"Yes. All data transmitted between your browser and our servers is encrypted using TLS 1.3. Your flashcard content and account information are stored in encrypted databases. We use industry-standard security practices including access controls, regular security audits, and vulnerability scanning. Payment data is handled entirely by Stripe and is never stored on our systems.\","),
p("      },"),
p("      {"),
p("        id: \"sell-data\","),
p("        question: \"Do you sell my data?\","),
p("        answer:"),
p("          \"No. We do not sell, rent, or trade your personal information or flashcard content to any third parties. We use anonymized, aggregated usage data internally to improve the product, but this data cannot be traced back to you individually. For full details, please review our Privacy Policy.\","),
p("      },"),
p("      {"),
p("        id: \"export-data\","),
p("        question: \"Can I export my data?\","),
p("        answer:"),
p("          \"Yes. You can export all of your flashcard decks at any time from the Account Settings page. Exports are available in JSON format (for re-importing into KognitDeck or other tools) and CSV format (for use in spreadsheets or other flashcard apps like Anki). You can also request a full copy of all data we hold about you by contacting our support team.\","),
p("      },"),
p("    ],"),
p("  },"),
p("];"),
p(""),
p("export default function FAQPage() {"),
p("  return ("),
p("    <div className=\"min-h-screen flex flex-col bg-gray-50\">"),
p("      <Navbar />"),
p("      <main className=\"flex-1\">"),
p("        {/* Hero */}"),
p("        <section className=\"bg-white border-b border-gray-200 py-16 px-4\">"),
p("          <div className=\"max-w-3xl mx-auto text-center\">"),
p("            <div className=\"inline-flex items-center justify-center w-16 h-16 rounded-full bg-blue-100 mb-6\">"),
p("              <HelpCircle className=\"w-8 h-8 text-blue-600\" />"),
p("            </div>"),
p("            <h1 className=\"text-4xl font-bold text-gray-900 mb-4\">"),
p("              Frequently Asked Questions"),
p("            </h1>"),
p("            <p className=\"text-lg text-gray-600\">"),
p("              Everything you need to know about KognitDeck. Cannot find your answer?{\" \"}"),
p("              <Link href=\"/contact\" className=\"text-blue-600 hover:underline font-medium\">"),
p("                Contact our support team."),
p("              </Link>"),
p("            </p>"),
p("          </div>"),
p("        </section>"),
p(""),
p("        {/* FAQ Sections */}"),
p("        <section className=\"max-w-3xl mx-auto px-4 py-16 space-y-14\">"),
p("          {faqSections.map((section) => ("),
p("            <div key={section.id}>"),
p("              <div className=\"flex items-center gap-3 mb-6\">"),
p("                <span"),
p("                  className={`inline-block px-3 py-1 rounded-full text-sm font-semibold ${section.badgeColor}`}"),
p("                >"),
p("                  {section.label}"),
p("                </span>"),
p("                <div className=\"flex-1 h-px bg-gray-200\" />"),
p("              </div>"),
p("              <Accordion type=\"single\" collapsible className=\"space-y-2\">"),
p("                {section.questions.map((item) => ("),
p("                  <AccordionItem"),
p("                    key={item.id}"),
p("                    value={item.id}"),
p("                    className=\"bg-white border border-gray-200 rounded-lg px-5 shadow-sm\""),
p("                  >"),
p("                    <AccordionTrigger className=\"text-left text-base font-medium text-gray-900 hover:text-blue-600 py-4\">"),
p("                      {item.question}"),
p("                    </AccordionTrigger>"),
p("                    <AccordionContent className=\"text-gray-600 leading-relaxed pb-4\">"),
p("                      {item.answer}"),
p("                    </AccordionContent>"),
p("                  </AccordionItem>"),
p("                ))}"),
p("              </Accordion>"),
p("            </div>"),
p("          ))}"),
p("        </section>"),
p(""),
p("        {/* CTA Banner */}"),
p("        <section className=\"bg-blue-600 py-14 px-4\">"),
p("          <div className=\"max-w-2xl mx-auto text-center\">"),
p("            <MessageCircle className=\"w-10 h-10 text-blue-200 mx-auto mb-4\" />"),
p("            <h2 className=\"text-2xl font-bold text-white mb-3\">Still have questions?</h2>"),
p("            <p className=\"text-blue-100 mb-8\">"),
p("              Our support team typically responds within a few hours on business days."),
p("            </p>"),
p("            <div className=\"flex flex-col sm:flex-row gap-3 justify-center\">"),
p("              <Button asChild size=\"lg\" className=\"bg-white text-blue-600 hover:bg-blue-50 font-semibold\">"),
p("                <Link href=\"/contact\">Contact Support</Link>"),
p("              </Button>"),
p("              <Button asChild size=\"lg\" variant=\"outline\" className=\"border-blue-300 text-white hover:bg-blue-700 font-semibold\">"),
p("                <Link href=\"/dashboard\">Go to Dashboard</Link>"),
p("              </Button>"),
p("            </div>"),
p("          </div>"),
p("        </section>"),
p("      </main>"),
p("      <Footer />"),
p("    </div>"),
p("  );"),
p("}")
);

fs.writeFileSync(base + "/faq/page.tsx", faq, "utf8");
console.log("FAQ page written: " + (faq.split("\n").length) + " lines");
// ===== TERMS PAGE =====
const terms = [
p("import { Navbar } from \"@/components/layout/Navbar\";"),
p("import { Footer } from \"@/components/layout/Footer\";"),
p("import { Button } from \"@/components/ui/button\";"),
p("import Link from \"next/link\";"),
p(""),
p("export default function TermsPage() {"),
p("  return ("),
p("    <div className=\"min-h-screen flex flex-col bg-white\">"),
p("      <Navbar />"),
p("      <main className=\"flex-1\">"),
p("        <div className=\"max-w-3xl mx-auto px-4 py-16\">"),
p("          {/* Header */}"),
p("          <div className=\"mb-10\">"),
p("            <h1 className=\"text-4xl font-bold text-gray-900 mb-3\">Terms of Service</h1>"),
p("            <p className=\"text-sm text-gray-500\">Last updated: February 2026</p>"),
p("          </div>"),
p(""),
p("          <div className=\"prose prose-gray max-w-none space-y-10\">"),
p("            {/* 1. Acceptance */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">1. Acceptance of Terms</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                By accessing or using KognitDeck (the \"Service\"), you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree to these Terms, please do not use the Service. These Terms apply to all visitors, users, and others who access or use the Service. By creating an account, you confirm that you are at least 13 years of age and have the legal capacity to enter into a binding agreement."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 2. Description */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">2. Description of Service</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                KognitDeck is an AI-powered flashcard generation and study platform. The Service allows users to generate flashcard decks from topics or text, study cards in various modes, take quizzes, and manage their learning content. We offer both a free tier and a paid subscription plan (\"Pro\"). Features available under each plan are described on our Pricing page and are subject to change with reasonable notice."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 3. User Accounts */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">3. User Accounts</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                To access most features of the Service, you must create an account. You agree to provide accurate, current, and complete information during registration and to update such information as necessary. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorized use of your account. KognitDeck will not be liable for any loss or damage arising from your failure to protect your account credentials."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 4. Subscription and Billing */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">4. Subscription and Billing</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                KognitDeck Pro is available on a monthly or annual subscription basis. By subscribing, you authorize us to charge the applicable fees to your payment method on a recurring basis until you cancel. Subscription fees are billed in advance. Prices are listed in USD and are subject to change with 30 days notice. You are responsible for any taxes applicable to your subscription. Payments are processed by Stripe, Inc. We do not store your payment card details on our servers."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 5. Acceptable Use */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">5. Acceptable Use</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed mb-3\">"),
p("                You agree to use the Service only for lawful purposes and in a manner that does not infringe the rights of others. You must not:"),
p("              </p>"),
p("              <ul className=\"list-disc pl-6 text-gray-600 space-y-1\">"),
p("                <li>Use the Service to generate content that is unlawful, harmful, threatening, abusive, defamatory, or otherwise objectionable.</li>"),
p("                <li>Attempt to gain unauthorized access to any part of the Service or its related systems.</li>"),
p("                <li>Use automated tools or scripts to scrape, crawl, or bulk-download content from the Service.</li>"),
p("                <li>Resell, sublicense, or commercially exploit the Service without our express written permission.</li>"),
p("                <li>Upload or transmit malware, viruses, or any other malicious code.</li>"),
p("              </ul>"),
p("            </section>"),
p(""),
p("            {/* 6. Intellectual Property */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">6. Intellectual Property</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                The Service and its original content, features, and functionality are and will remain the exclusive property of KognitDeck and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without our prior written consent. The flashcard content you generate through the Service using your own inputs remains your property. By using the Service, you grant KognitDeck a limited, non-exclusive, royalty-free license to store and display your content solely for the purpose of providing the Service to you."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 7. Privacy */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">7. Privacy</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. Please review our Privacy Policy to understand our practices. By using the Service, you consent to the collection and use of your information as described in our Privacy Policy."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 8. Disclaimers */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">8. Disclaimers</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                THE SERVICE IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. KognitDeck does not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components. AI-generated flashcard content is provided for educational convenience and may contain errors or inaccuracies. You are responsible for verifying the accuracy of generated content."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 9. Limitation of Liability */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">9. Limitation of Liability</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL CARDCRAFT, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICE. IN NO EVENT SHALL OUR AGGREGATE LIABILITY EXCEED THE GREATER OF ONE HUNDRED DOLLARS ($100) OR THE AMOUNT YOU PAID TO CARDCRAFT IN THE PAST SIX MONTHS."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 10. Refund Policy */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">10. Refund Policy</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                We offer a 7-day money-back guarantee on new Pro subscriptions. If you are not satisfied with your purchase, contact our support team within 7 days of your initial payment and we will issue a full refund, no questions asked. Refunds are not available for subsequent billing cycles or for accounts that have violated these Terms. Refunds are processed within 5 to 10 business days and will be returned to your original payment method."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 11. Termination */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">11. Termination</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                We reserve the right to suspend or terminate your account and access to the Service at our sole discretion, without prior notice, if we believe you have violated these Terms, engaged in fraudulent or illegal activity, or for any other reason we deem appropriate. Upon termination, your right to use the Service will immediately cease. You may terminate your account at any time by contacting our support team or through your account settings. Provisions of these Terms that by their nature should survive termination shall survive."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 12. Changes */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">12. Changes to Terms</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 14 days notice via email or a prominent notice on the Service before the new terms take effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use the Service after revisions become effective, you agree to be bound by the updated Terms."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 13. Contact */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">13. Contact</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                If you have any questions about these Terms of Service, please contact us at:"),
p("              </p>"),
p("              <div className=\"mt-4 p-5 bg-gray-50 rounded-lg border border-gray-200\">"),
p("                <p className=\"text-gray-700 font-medium\">KognitDeck</p>"),
p("                <p className=\"text-gray-600\">Email: legal@kognitdeck.app</p>"),
p("                <p className=\"text-gray-600 mt-3\">"),
p("                  You can also reach us via the{\" \"}"),
p("                  <Link href=\"/contact\" className=\"text-blue-600 hover:underline\">"),
p("                    contact form"),
p("                  </Link>"),
p("                  {\" \"}on our website."),
p("                </p>"),
p("              </div>"),
p("            </section>"),
p("          </div>"),
p(""),
p("          {/* Bottom Navigation */}"),
p("          <div className=\"mt-16 pt-8 border-t border-gray-200 flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between\">"),
p("            <p className=\"text-sm text-gray-500\">"),
p("              Questions about our terms?{\" \"}"),
p("              <Link href=\"/faq\" className=\"text-blue-600 hover:underline\">"),
p("                View our FAQ"),
p("              </Link>"),
p("            </p>"),
p("            <div className=\"flex gap-3\">"),
p("              <Button asChild variant=\"outline\" size=\"sm\">"),
p("                <Link href=\"/privacy\">Privacy Policy</Link>"),
p("              </Button>"),
p("              <Button asChild size=\"sm\" className=\"bg-blue-600 hover:bg-blue-700 text-white\">"),
p("                <Link href=\"/\">Back to Home</Link>"),
p("              </Button>"),
p("            </div>"),
p("          </div>"),
p("        </div>"),
p("      </main>"),
p("      <Footer />"),
p("    </div>"),
p("  );"),
p("}")
].join("\n");

fs.writeFileSync(base + "/terms/page.tsx", terms, "utf8");
console.log("Terms page written: " + (terms.split("\n").length) + " lines");
// ===== PRIVACY PAGE =====
const privacy = [
p("import { Navbar } from \"@/components/layout/Navbar\";"),
p("import { Footer } from \"@/components/layout/Footer\";"),
p("import { Button } from \"@/components/ui/button\";"),
p("import Link from \"next/link\";"),
p(""),
p("export default function PrivacyPage() {"),
p("  return ("),
p("    <div className=\"min-h-screen flex flex-col bg-white\">"),
p("      <Navbar />"),
p("      <main className=\"flex-1\">"),
p("        <div className=\"max-w-3xl mx-auto px-4 py-16\">"),
p("          <div className=\"mb-10\">"),
p("            <h1 className=\"text-4xl font-bold text-gray-900 mb-3\">Privacy Policy</h1>"),
p("            <p className=\"text-sm text-gray-500\">Last updated: February 2026</p>"),
p("          </div>"),
p(""),
p("          <div className=\"prose prose-gray max-w-none space-y-10\">"),
p(""),
p("            {/* 1. Introduction */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">1. Introduction</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                Welcome to KognitDeck. We respect your privacy and are committed to protecting the personal information you share with us. This Privacy Policy explains how KognitDeck (\"we\", \"us\", or \"our\") collects, uses, stores, and shares information about you when you use our website and services (collectively, the \"Service\"). By using the Service, you agree to the collection and use of information in accordance with this policy."),
p("              </p>"),
p("            </section>"),
p(""),
p("            {/* 2. Information We Collect */}"),
p("            <section>"),
p("              <h2 className=\"text-2xl font-semibold text-gray-900 mb-3\">2. Information We Collect</h2>"),
p("              <p className=\"text-gray-600 leading-relaxed mb-4\">We collect the following types of information:</p>"),
p("              <h3 className=\"text-lg font-semibold text-gray-800 mb-2\">Account Information</h3>"),
p("              <p className=\"text-gray-600 leading-relaxed mb-4\">"),
p("                When you create an account, we collect your name, email address, and a hashed password. If you sign in via Google OAuth, we receive your name, email address, and Google profile picture from Google. We do not receive or store your Google account password."),
p("              </p>"),
p("              <h3 className=\"text-lg font-semibold text-gray-800 mb-2\">Usage Data</h3>"),
p("              <p className=\"text-gray-600 leading-relaxed mb-4\">"),
p("                We automatically collect information about how you interact with the Service, including the pages you visit, the features you use, the flashcard topics you generate, timestamps, device type, browser type, and IP address. This information helps us understand how the Service is used and where we can improve."),
p("              </p>"),
p("              <h3 className=\"text-lg font-semibold text-gray-800 mb-2\">Payment Information</h3>"),
p("              <p className=\"text-gray-600 leading-relaxed\">"),
p("                All payment processing is handled by Stripe, Inc. When you subscribe to KognitDeck Pro, your payment card details are transmitted directly to Stripe and are never stored on our servers. We receive from Stripe only a tokenized reference to your payment method and high-level transaction information such as subscription status and billing dates."),
p("              </p>"),
p("            </section>"),
// ===== PRIVACY PAGE =====
const privacy = [
p("import { Navbar } from "@/components/layout/Navbar";"),
p("import { Footer } from "@/components/layout/Footer";"),
p("import { Button } from "@/components/ui/button";"),
p("import Link from "next/link";"),
p(""),
p("export default function PrivacyPage() {"),
p("  return ("),
p("    <div className="min-h-screen flex flex-col bg-white">"),
p("      <Navbar />"),
p("      <main className="flex-1">"),
p("        <div className="max-w-3xl mx-auto px-4 py-16">"),
p("          <div className="mb-10">"),
p("            <h1 className="text-4xl font-bold text-gray-900 mb-3">Privacy Policy</h1>"),
p("            <p className="text-sm text-gray-500">Last updated: February 2026</p>"),
p("          </div>"),
p(""),
p("          <div className="prose prose-gray max-w-none space-y-10">"),
p("{/* 1. Introduction */}"),
p("            <section>"),
p("              <h2 className="text-2xl font-semibold text-gray-900 mb-3">1. Introduction</h2>"),
p("              <p className="text-gray-600 leading-relaxed">"),
p("                Welcome to KognitDeck. We respect your privacy and are committed to protecting the personal information you share with us. This Privacy Policy explains how KognitDeck ("we", "us", or "our") collects, uses, stores, and shares information about you when you use our website and services (collectively, the "Service"). By using the Service, you agree to the collection and use of information in accordance with this policy."),
p("              </p>"),
p("            </section>"),
p(""),
p("{/* 2. Information We Collect */}"),
p("            <section>"),
p("              <h2 className="text-2xl font-semibold text-gray-900 mb-3">2. Information We Collect</h2>"),
p("              <p className="text-gray-600 leading-relaxed mb-4">We collect the following types of information:</p>"),
p("              <h3 className="text-lg font-semibold text-gray-800 mb-2">Account Information</h3>"),
p("              <p className="text-gray-600 leading-relaxed mb-4">"),
p("                When you create an account, we collect your name, email address, and a hashed password. If you sign in via Google OAuth, we receive your name, email address, and Google profile picture from Google. We do not receive or store your Google account password."),
p("              </p>"),
p("              <h3 className="text-lg font-semibold text-gray-800 mb-2">Usage Data</h3>"),
p("              <p className="text-gray-600 leading-relaxed mb-4">"),
p("                We automatically collect information about how you interact with the Service, including the pages you visit, the features you use, the flashcard topics you generate, timestamps, device type, browser type, and IP address. This helps us understand how the Service is used and where we can improve."),
p("              </p>"),
p("              <h3 className="text-lg font-semibold text-gray-800 mb-2">Payment Information</h3>"),
p("              <p className="text-gray-600 leading-relaxed">"),
p("                All payment processing is handled by Stripe, Inc. When you subscribe to KognitDeck Pro, your payment card details are transmitted directly to Stripe and are never stored on our servers. We receive from Stripe only a tokenized reference to your payment method and high-level transaction information such as subscription status and billing dates."),
p("              </p>"),
p("            </section>"),
p(""),
p("{/* 3. How We Use Info */}"),
p("            <section>"),
p("              <h2 className="text-2xl font-semibold text-gray-900 mb-3">3. How We Use Your Information</h2>"),
p("              <p className="text-gray-600 leading-relaxed mb-3">We use the information we collect to:</p>"),
p("              <ul className="list-disc pl-6 text-gray-600 space-y-1">"),
p("                <li>Provide, operate, and maintain the Service.</li>"),
p("                <li>Process your subscription payments and send billing-related communications.</li>"),
p("                <li>Send you transactional emails such as account confirmations, password resets, and subscription receipts.</li>"),
p("                <li>Respond to your support requests and inquiries.</li>"),
p("                <li>Monitor and analyze usage patterns to improve the Service.</li>"),
p("                <li>Detect, prevent, and address technical issues and fraudulent activity.</li>"),
p("                <li>Send you product updates and promotional communications, with an easy opt-out at any time.</li>"),
p("              </ul>"),
p("            </section>"),
p(""),
p("{/* 4. Data Storage */}"),
p("            <section>"),
p("              <h2 className="text-2xl font-semibold text-gray-900 mb-3">4. Data Storage and Security</h2>"),
p("              <p className="text-gray-600 leading-relaxed">"),
p("                Your data is stored on servers located in the United States. We implement industry-standard security measures including TLS encryption for data in transit, AES-256 encryption for sensitive data at rest, and strict access controls. While we take the protection of your data seriously, no method of electronic storage is 100% secure. We will notify you promptly if we become aware of a breach affecting your data."),
p("              </p>"),
p("            </section>"),
p(""),
p("{/* 5. Cookies */}"),
p("            <section>"),
p("              <h2 className="text-2xl font-semibold text-gray-900 mb-3">5. Cookies</h2>"),
p("              <p className="text-gray-600 leading-relaxed">"),
p("                We use cookies and similar tracking technologies to maintain your session, remember your preferences, and analyze how the Service is used. Essential cookies are required for the Service to function and cannot be disabled. You can configure your browser to refuse non-essential cookies, but doing so may affect certain features of the Service."),
p("              </p>"),
p("            </section>"),
p(""),
p("{/* 6. Third-Party Services */}"),
p("            <section>"),
p("              <h2 className="text-2xl font-semibold text-gray-900 mb-3">6. Third-Party Services</h2>"),
p("              <p className="text-gray-600 leading-relaxed mb-3">We use the following third-party services that may process your personal data:</p>"),
p("              <ul className="list-disc pl-6 text-gray-600 space-y-2">"),
p("                <li><strong>Stripe</strong> &mdash; Used for payment processing. Stripe is PCI DSS Level 1 certified. Your payment information is governed by Stripe's Privacy Policy.</li>"),
p("                <li><strong>Google OAuth</strong> &mdash; Used for social sign-in. If you choose to sign in with Google, your data is also governed by Google's Privacy Policy.</li>"),
p("                <li><strong>Analytics</strong> &mdash; We may use analytics tools to understand usage patterns. Where possible, analytics data is anonymized and aggregated before processing.</li>"),
p("              </ul>"),
p("              <p className="text-gray-600 leading-relaxed mt-3">"),
p("                We do not sell your personal information to any third parties. We share your information only as described in this policy or with your explicit consent."),
p("              </p>"),
p("            </section>"),
p(""),
p("{/* 7. Data Retention */}"),
p("            <section>"),
p("              <h2 className="text-2xl font-semibold text-gray-900 mb-3">7. Data Retention</h2>"),
p("              <p className="text-gray-600 leading-relaxed">"),
p("                We retain your personal information for as long as your account is active or as needed to provide you the Service. If you request deletion of your account, we will delete or anonymize your personal data within 30 days, except where we are required to retain it for legal or regulatory purposes. Anonymized and aggregated data may be retained indefinitely for analytics purposes."),
p("              </p>"),
p("            </section>"),
p(""),
p("{/* 8. Your Rights */}"),
p("            <section>"),
p("              <h2 className="text-2xl font-semibold text-gray-900 mb-3">8. Your Rights</h2>"),
p("              <p className="text-gray-600 leading-relaxed mb-3">Depending on your location, you may have the following rights regarding your personal data:</p>"),
p("              <ul className="list-disc pl-6 text-gray-600 space-y-1">"),
p("                <li><strong>Access:</strong> Request a copy of the personal data we hold about you.</li>"),
p("                <li><strong>Correction:</strong> Request that we correct inaccurate or incomplete data.</li>"),
p("                <li><strong>Deletion:</strong> Request that we delete your personal data.</li>"),
p("                <li><strong>Export:</strong> Download your flashcard decks and account data in a portable format.</li>"),
p("                <li><strong>Opt-out:</strong> Unsubscribe from marketing emails at any time using the link in the email footer.</li>"),
p("              </ul>"),
p("              <p className="text-gray-600 leading-relaxed mt-3">To exercise any of these rights, contact us at privacy@kognitdeck.app or through your account settings.</p>"),
p("            </section>"),
